// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package stress

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewStressor() Stressor {
	stressorImpl := &StressorImpl{}
	return stressorImpl
}

// wire.go:

var DefaultSet = wire.NewSet(wire.Struct(new(StressorImpl), "*"), wire.Bind(new(Stressor), new(*StressorImpl)))

var buildSet = DefaultSet
